/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.UsuarioDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author tony
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        CAJERO = new javax.swing.JLabel();
        citylogo = new javax.swing.JLabel();
        tituloIniciar = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PinLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPin = new javax.swing.JPasswordField();
        entrarbtn = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setDoubleBuffered(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 150, 190));

        CAJERO.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        CAJERO.setForeground(new java.awt.Color(255, 255, 255));
        CAJERO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CAJERO.setText("CIELO AZUL");
        background.add(CAJERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 290, 30));

        citylogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/city.png"))); // NOI18N
        citylogo.setText("jLabel1");
        background.add(citylogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        tituloIniciar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        tituloIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favicon.png"))); // NOI18N
        tituloIniciar.setText("INICIAR SESIÓN");
        background.add(tituloIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 260, 40));

        idLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        idLabel.setText("ID USUARIO");
        background.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 380, 10));

        PinLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        PinLabel.setText("PIN");
        background.add(PinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 50, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 380, 20));

        txtPin.setForeground(new java.awt.Color(204, 204, 204));
        txtPin.setText("****");
        txtPin.setBorder(null);
        txtPin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPinMousePressed(evt);
            }
        });
        background.add(txtPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 370, -1));

        entrarbtn.setBackground(new java.awt.Color(0, 134, 190));

        btnIngresar.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 0, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresar.setText("ENTRAR");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout entrarbtnLayout = new javax.swing.GroupLayout(entrarbtn);
        entrarbtn.setLayout(entrarbtnLayout);
        entrarbtnLayout.setHorizontalGroup(
            entrarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        entrarbtnLayout.setVerticalGroup(
            entrarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(entrarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 130, 50));

        txtIdUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtIdUsuario.setText("Ingrese su ID");
        txtIdUsuario.setBorder(null);
        txtIdUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdUsuarioMousePressed(evt);
            }
        });
        background.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 370, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int intentos = 0;

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
         try {
            int id = Integer.parseInt(txtIdUsuario.getText());
            String pin = new String(txtPin.getPassword());

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            Usuario usuario = usuarioDAO.autenticarUsuario(id, pin);

            if (usuario == null) {
                intentos++;
                if (intentos >= 3) {
                    JOptionPane.showMessageDialog(this, "PIN incorrecto 3 veces. Tarjeta retenida.");
                    btnIngresar.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this, "PIN incorrecto. Intento " + intentos + " de 3.");
                }
            } else {
                new MenuFrame(usuario).setVisible(true);
                this.dispose();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        // TODO add your handling code here:
        entrarbtn.setBackground(new Color(20,156,233));
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        // TODO add your handling code here:
        entrarbtn.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_btnIngresarMouseExited

    private void txtPinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPinMousePressed
        if (String.valueOf(txtPin.getPassword()).equals("****")) {
            txtPin.setText("");
            txtPin.setForeground(Color.black);
        }
        if (txtIdUsuario.getText().isEmpty()) {
            txtIdUsuario.setText("Ingrese su ID");
            txtIdUsuario.setForeground(Color.gray);
        }
        
        
    }//GEN-LAST:event_txtPinMousePressed

    private void txtIdUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdUsuarioMousePressed
        // TODO add your handling code here:
        if (txtIdUsuario.getText().equals("Ingrese su ID")) {
            txtIdUsuario.setText("");
            txtIdUsuario.setForeground(Color.black);
        }
        if (String.valueOf(txtPin.getPassword()).isEmpty()) {
            txtPin.setText("****");
            txtPin.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtIdUsuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CAJERO;
    private javax.swing.JLabel PinLabel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnIngresar;
    private javax.swing.JLabel citylogo;
    private javax.swing.JPanel entrarbtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel tituloIniciar;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JPasswordField txtPin;
    // End of variables declaration//GEN-END:variables
}
