/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import modelo.Usuario;

/**
 *
 * @author tony
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    private Usuario usuario;
    public MenuFrame(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
        bien.setText("¡Hola, " + usuario.getNombre() + "!");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenido = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnConsultarSaldo = new javax.swing.JLabel();
        lblMembrete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnRetirarEfectivo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnDepositarEfectivo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        bien = new javax.swing.JLabel();
        fondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultarSaldo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnConsultarSaldo.setForeground(new java.awt.Color(0, 134, 190));
        btnConsultarSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsultarSaldo.setText("CONSULTAR SALDO");
        btnConsultarSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarSaldoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelContenido.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, 100));

        lblMembrete.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 134, 190));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favicon.png"))); // NOI18N
        jLabel1.setText("CIELO AZUL");

        javax.swing.GroupLayout lblMembreteLayout = new javax.swing.GroupLayout(lblMembrete);
        lblMembrete.setLayout(lblMembreteLayout);
        lblMembreteLayout.setHorizontalGroup(
            lblMembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMembreteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(639, Short.MAX_VALUE))
        );
        lblMembreteLayout.setVerticalGroup(
            lblMembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMembreteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContenido.add(lblMembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        btnRetirarEfectivo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnRetirarEfectivo.setForeground(new java.awt.Color(0, 134, 190));
        btnRetirarEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRetirarEfectivo.setText("RETIRAR EFECTIVO");
        btnRetirarEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirarEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarEfectivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRetirarEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRetirarEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelContenido.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 340, 100));

        btnDepositarEfectivo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnDepositarEfectivo.setForeground(new java.awt.Color(0, 134, 190));
        btnDepositarEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDepositarEfectivo.setText("DEPOSITAR EFECTIVO");
        btnDepositarEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepositarEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepositarEfectivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDepositarEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDepositarEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelContenido.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 340, 100));

        btnCerrarSesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 134, 190));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelContenido.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 340, -1));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("¿QUÉ DESEA HACER HOY?");
        panelContenido.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        bien.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bien.setForeground(new java.awt.Color(255, 255, 255));
        bien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bien.setText("Hola, ");
        panelContenido.add(bien, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 60, 310, 48));

        fondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AzulChat.png"))); // NOI18N
        fondoAzul.setText("jLabel6");
        panelContenido.add(fondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose(); // Cierra login
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnConsultarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoMouseClicked
        // TODO add your handling code here:
        
        ConsultarSaldoFrame saldoFrame = new ConsultarSaldoFrame(this.usuario);
        saldoFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarSaldoMouseClicked

    private void btnRetirarEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarEfectivoMouseClicked
        // TODO add your handling code here:
        RetiroFrame retiroFrame = new RetiroFrame(this.usuario);
        retiroFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRetirarEfectivoMouseClicked

    private void btnDepositarEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositarEfectivoMouseClicked
        // TODO add your handling code here:
        DepositoFrame depositoFrame = new DepositoFrame(this.usuario);
        depositoFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnDepositarEfectivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bien;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JLabel btnConsultarSaldo;
    private javax.swing.JLabel btnDepositarEfectivo;
    private javax.swing.JLabel btnRetirarEfectivo;
    private javax.swing.JLabel fondoAzul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel lblMembrete;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
