/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JTextField;
import modelo.ATM;
import modelo.Usuario;

/**
 *
 * @author tony
 */
public class RetiroFrame extends javax.swing.JFrame {
    
    private Usuario usuario;
    private ATM atm;
    /**
     * Creates new form RetiroFrame
     */
    public RetiroFrame(Usuario usuario) {
        this.usuario = usuario;
        this.atm = new ATM(usuario);
        initComponents();
        this.setLocationRelativeTo(null); 
        agregarListeners();
    }
    
    private void agregarListeners() {
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                lblResultado.setText(""); 
            }
        });
    }
    
     private void agregarMonto(JTextField campo, double monto) {
        try {
            double actual = Double.parseDouble(campo.getText());
            txtMonto.setText(String.format("%.2f", actual + monto));
        } catch (NumberFormatException e) {
            txtMonto.setText(String.format("%.2f", monto));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membrete = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblPesos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl50 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl100 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl1000 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl5000 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl500 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblCerrarSesion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        fondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 134, 190));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favicon.png"))); // NOI18N
        jLabel2.setText("CIELO AZUL");

        javax.swing.GroupLayout membreteLayout = new javax.swing.GroupLayout(membrete);
        membrete.setLayout(membreteLayout);
        membreteLayout.setHorizontalGroup(
            membreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(membreteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(640, Short.MAX_VALUE))
        );
        membreteLayout.setVerticalGroup(
            membreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(membreteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(membrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INGRESE EL MONTO A RETIRAR");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 76, -1, 40));

        txtMonto.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 50));

        lblPesos.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblPesos.setForeground(new java.awt.Color(255, 255, 255));
        lblPesos.setText("$");
        getContentPane().add(lblPesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lbl50.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl50.setForeground(new java.awt.Color(0, 134, 190));
        lbl50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl50.setText("$50.00");
        lbl50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl50MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl50, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 220, 70));

        lbl100.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl100.setForeground(new java.awt.Color(0, 134, 190));
        lbl100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl100.setText("$100.00");
        lbl100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl100MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl100, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl100, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 230, -1));

        lbl1000.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl1000.setForeground(new java.awt.Color(0, 134, 190));
        lbl1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1000.setText("$1,000.00");
        lbl1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1000MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1000, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1000, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 220, -1));

        lbl5000.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl5000.setForeground(new java.awt.Color(0, 134, 190));
        lbl5000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5000.setText("$5,000.00");
        lbl5000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl5000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5000MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl5000, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl5000, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 230, -1));

        lbl500.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl500.setForeground(new java.awt.Color(0, 134, 190));
        lbl500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl500.setText("$500.00");
        lbl500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl500MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl500, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl500, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 220, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 134, 190));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("$10,000");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 220, -1));

        lblRegresar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(0, 134, 190));
        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegresar.setText("REGRESAR");
        lblRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 290, 70));

        lblCerrarSesion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(0, 134, 190));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrarSesion.setText("CERRAR SESIÓN");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, 70));

        jPanel4.setBackground(new java.awt.Color(102, 255, 51));

        btnAceptar.setBackground(new java.awt.Color(102, 204, 0));
        btnAceptar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 90, 40));

        lblResultado.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 134, 190));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 670, 50));

        fondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AzulChat.png"))); // NOI18N
        fondoAzul.setText("jLabel1");
        getContentPane().add(fondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMontoActionPerformed

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
        // TODO add your handling code here:
        new MenuFrame(usuario).setVisible(true); // Abre menú principal
        this.dispose(); // Cierra login
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose(); // Cierra login
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:
        try {
                double monto = Double.parseDouble(txtMonto.getText());

                if (atm.retirar(monto)) {
                    lblResultado.setText("Retiro exitoso. Saldo actual: $" + usuario.getSaldo());
                    txtMonto.setText("");
                } else {
                    lblResultado.setText("Error: saldo insuficiente o monto inválido.");
                    txtMonto.setText("");
                }
            } catch (NumberFormatException ex) {
                lblResultado.setText("Ingrese un número válido.");
                txtMonto.setText("");
            }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void lbl50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl50MouseClicked
        // TODO add your handling code here:
        //txtMonto.setText("50.00");
        agregarMonto(txtMonto, 50.00);
        lblResultado.setText("");
    }//GEN-LAST:event_lbl50MouseClicked

    private void lbl100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl100MouseClicked
        // TODO add your handling code here:
        //txtMonto.setText("100.00");
        agregarMonto(txtMonto, 100.00);
        lblResultado.setText("");
    }//GEN-LAST:event_lbl100MouseClicked

    private void lbl500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl500MouseClicked
        // TODO add your handling code here:
        //txtMonto.setText("500.00");
        agregarMonto(txtMonto, 500.00);
        lblResultado.setText("");
    }//GEN-LAST:event_lbl500MouseClicked

    private void lbl1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1000MouseClicked
        // TODO add your handling code here:
        //txtMonto.setText("1000.00");
        agregarMonto(txtMonto, 1000.00);
        lblResultado.setText("");
    }//GEN-LAST:event_lbl1000MouseClicked

    private void lbl5000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5000MouseClicked
        // TODO add your handling code here:
        //txtMonto.setText("5000.00");
        agregarMonto(txtMonto, 5000.00);
        lblResultado.setText("");
    }//GEN-LAST:event_lbl5000MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //txtMonto.setText("10000.00");
        agregarMonto(txtMonto, 10000.00);
        lblResultado.setText("");
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetiroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetiroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetiroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetiroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RetiroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel fondoAzul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl100;
    private javax.swing.JLabel lbl1000;
    private javax.swing.JLabel lbl50;
    private javax.swing.JLabel lbl500;
    private javax.swing.JLabel lbl5000;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblPesos;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel membrete;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
